export const COUNTER__COUNT_UP = 'COUNTER__COUNT_UP';
export const COUNTER__COUNT_DOWN = 'COUNTER__COUNT_DOWN';
export const COUNTER__COUNT_RESET = 'COUNTER__COUNT_RESET';
export const COUNTER__SET_INTERVAL_UP = 'COUNTER__SET_INTERVAL_DOWN';
export const COUNTER__SET_INTERVAL_DOWN = 'COUNTER__SET_INTERVAL_UP';
export const COUNTER__CLEAR_INTERVAL = 'COUNTER__CLEAR_INTERVAL';
