export const LEADERBOARD__SET_EASY = 'LEADERBOARD__SET_EASY';
export const LEADERBOARD__SET_MEDIUM = 'LEADERBOARD__SET_MEDIUM';
export const LEADERBOARD__SET_HARD = 'LEADERBOARD__SET_HARD';

export const LEADERBOARD__ADD_EASY = 'LEADERBOARD__ADD_EASY';
export const LEADERBOARD__ADD_MEDIUM = 'LEADERBOARD__ADD_MEDIUM';
export const LEADERBOARD__ADD_HARD = 'LEADERBOARD__ADD_HARD';

export const LEADERBOARD__DELETE_EASY = 'LEADERBOARD__DELETE_EASY';
export const LEADERBOARD__DELETE_MEDIUM = 'LEADERBOARD__DELETE_MEDIUM';
export const LEADERBOARD__DELETE_HARD = 'LEADERBOARD__DELETE_HARD';
